* Nullreff's config files

These are the custom configuration files used to run my computer.
They're very specific to my own setup but feel free to draw inspiration or copy them to your own setup.
As much as I try to automate, not everything can be automatically setup across multiple operating systems and machines.
Therefore this readme contains all the documentation for how I configure my machines.

** Installing

For a simple setup, clone this into your =.config= folder and run =./setup= to install everything.
For a more advanced explanation read on...

For a more advanced install Debian from a usb stick with full disk encryption and no gui.

#+BEGIN_SRC
su -l
apt install sudo curl
usermod nullreff -aG sudo
su nullreff
curl https://nullreff.net/install | bash
#+END_SRC

Rather than running the full =./setup= script you run individual scripts from the [[/scripts/]] folder.
For more details on how to setup various things, check out [[/docs/]] folder and read the comments I have in the install scritps and config files.

** Design

Pretty much everything in this repo is built to run on top of Debian or Android
This is for a few key reasons:

1. They are ubiquitous across pretty much everything. The vast majority of software is built to support them. Having a configuration that can move from install to install and expect to work well for just about everything I do is important to me. There are plenty of other cool operating systems that I love for their philosophy and tech but none are as universally supported. If that changes and other systems gain more universal acceptance, I may be more inclined to swap.
2. They are flexible in that I can tailor the system to my needs and pick between different flavors.  For example, Debain offers a rock solid platform that doesn't break (stable) to a more up to date environment (testing) to a rolling release with the latest stuff (unstable). While Android may not be the most secure/private system, it has plenty of derivative distributions that solve this problem.
3. They have plenty of information available online. If something breaks you can bet that someone else has also had it break and probably already found a solution. This saves me time over being the first/only person to troubleshoot an issue on a newer or more obscure distro.

For my core devices, I currently use:

- Debian Unstable for my personal computers
- Debian Stable for my servers
- Calyx OS for my phones


