#!/bin/bash -e

cd ~/.config/

# Get all our software source and packages up to date
sudo cp files/sources.list /etc/apt/sources.list
sudo apt-get update
sudo apt-get dist-upgrade -y
sudo apt-get install -y grep

# Most software we can install using package managers
sudo apt-get install -y $(grep -vE "^\s*#" packages/apt.txt  | tr "\n" " ")

./scripts/link-configs

# Some software we have to build or install using a script
./scripts/install-fish
./scripts/install-networking
./scripts/install-sway
./scripts/install-ly
./scripts/install-kanshi
./scripts/install-alacritty
./scripts/install-firefox-developer-edition
./scripts/install-liquorix
./scripts/install-vim
./scripts/install-doom-emacs
./scripts/install-ruby
./scripts/install-nodejs
./scripts/install-bitwarden
./scripts/install-libreoffice
./scripts/install-printing
./scripts/install-rust
./scripts/install-wluma
./scripts/install-thunar
./scripts/install-nix
./scripts/install-protonvpn

sudo apt autoremove
