#!/bin/bash -e
cd ~/.config/
sudo cp files/sources.list /etc/apt/sources.list
sudo apt-get update
sudo apt-get dist-upgrade -y
sudo apt-get install -y grep
sudo apt-get install -y $(grep -vE "^\s*#" packages/apt.txt  | tr "\n" " ")
sudo snap install $(grep -vE "^\s*#" packages/snap.txt  | tr "\n" " ")
./bin/link-configs
./bin/install-ly
