#!/bin/bash -e

cd ~/.config/

# Get all our software source and packages up to date
sudo cp files/sources.list /etc/apt/sources.list
sudo apt-get update
sudo apt-get dist-upgrade -y
sudo apt-get install -y grep

# Most software we can install using package managers
sudo apt-get install -y $(grep -vE "^\s*#" packages/apt.txt  | tr "\n" " ")
sudo snap install $(grep -vE "^\s*#" packages/snap.txt  | tr "\n" " ")
./bin/link-configs

# Some software we have to build or install using a script
./bin/install-ly
./bin/install-firefox-developer-edition
