#!/bin/bash -e

yay -Sy nginx

sudo mkdir -p /etc/nginx/sites-{available,enabled}
sudo cp ~/.config/files/nginx_default /etc/nginx/sites-available/default
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

mkdir -p ~/.config/files/go.nullreff.net/
~/.config/scripts/build-go.nullreff.net
chmod 755 /home/nullreff

sudo systemctl restart nginx
