#!/bin/bash -e
sudo apt-get install emacs git ripgrep findutils fd-find cmake libtool-bin
if [ -d ~/.emacs.d ]; then
    exit
fi

git clone --depth 1 https://github.com/hlissner/doom-emacs ~/.emacs.d

# Prevent installer from asking us if we want an envvar file
mkdir -p ~/.emacs.d/.local/
touch ~/.emacs.d/.local/env

expect <<EOF
spawn ~/.emacs.d/bin/doom install
expect "Download and install all-the-icon's fonts?"
send "y\n"
expect eof
EOF
