#!/bin/bash -e
sudo apt-get install emacs git ripgrep findutils fd-find
git clone --depth 1 https://github.com/hlissner/doom-emacs ~/.emacs.d

# Prevent installer from asking us if we want an envvar file
mkdir -p ~/.emacs.d/.local/
touch ~/.emacs.d/.local/env

~/.emacs.d/bin/doom install
~/.emacs.d/bin/doom upgrade
