#!/bin/bash -e

yay -Sy rclone fuse

sudo cp ~/.config/files/fuse.conf /etc/fuse.conf

mkdir -p ~/remote ~/.cache/rclone/remote/

systemctl --user enable rclone-remote.service
systemctl --user start rclone-remote.service

mkdir -p ~/.cache/rclone/webdav/

systemctl --user enable rclone-webdav.service
systemctl --user start rclone-webdav.service
