#!/bin/bash -e

# Disable lightdm before we install ly
if [ $(systemctl list-unit-files "lighdm*" | wc -l) -gt 3 ]; then
    sudo apt-get purge -y lightdm
    sudo systemctl disable lightdm.service
fi

# Disable ssdm
if [ $(systemctl list-unit-files "sddm*" | wc -l) -gt 3 ]; then
    sudo systemctl disable sddm.service
fi

sudo apt-get install -y build-essential libpam0g-dev libxcb-xkb-dev

mkdir -p ~/src/
if [ ! -d ~/src/ly/ ]; then
    git clone --recurse-submodules https://github.com/nullgemm/ly.git ~/src/ly/
fi

cd ~/src/ly/
git pull

make
sudo make install
sudo systemctl enable ly.service
sudo systemctl disable getty@tty3.service
