#!/bin/bash -e

sudo apt install -y curl

if [ ! -f Miniconda3-latest-Linux-x86_64.sh ]; then
    mkdir -p ~/downloads/
    cd ~/downloads/
    curl -O https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
    sh Miniconda3-latest-Linux-x86_64.sh
fi
    
