#!/bin/bash -e

sudo apt install -y rclone fuse

mkdir -p ~/remote ~/.cache/rclone/remote/

systemctl --user enable rclone-remote.service
systemctl --user start rclone-remote.service

mkdir -p ~/.cache/rclone/webdav/

systemctl --user enable rclone-webdav.service
systemctl --user start rclone-webdav.service
