#!/bin/bash -e

sudo apt install -y network-manager

# Mac address randomization messes with wifi discovery, disable it
sudo cp ~/.config/files/30-mac-randomization.conf /etc/NetworkManager/conf.d/30-mac-randomization.conf
sudo systemctl restart NetworkManager
