#!/bin/bash -e

sudo apt install -y wget zenity

if [ ! -f ~/downloads/steam.deb ]; then
    mkdir -p ~/downloads/
    cd ~/downloads/
    wget https://cdn.akamai.steamstatic.com/client/installer/steam.deb
fi

sudo dpkg -i ~/downloads/steam.deb

# Fixes issues with steamvr breaking
# https://github.com/ValveSoftware/SteamVR-for-Linux/issues/234
sudo setcap CAP_SYS_NICE+ep ~/.local/share/Steam/steamapps/common/SteamVR/bin/linux64/vrcompositor-launcher

