#!/bin/bash -e
sudo apt-get install -y build-essential libpam0g-dev libxcb-xkb-dev
sudo apt-get purge -y lightdm

mkdir -p ~/src/
if [! -d ~/src/ly/ ]; then
    git clone https://github.com/nullgemm/ly.git ~/src/ly/
fi

cd ~/src/ly/
git pull

make github
make
sudo make install
sudo systemctl enable ly.service
sudo systemctl disable getty@tty3.service
