#!/bin/sh

# Clean up after GDM
xprop -root -remove _NET_NUMBER_OF_DESKTOPS \
      -remove _NET_DESKTOP_NAMES \
      -remove _NET_CURRENT_DESKTOP 2> /dev/null

# Run autostart stuff
sh /usr/lib/xmonad/xmonad-autostart &

# Run Xmonad
exec /usr/bin/xmonad 
