* VR

Currently use SteamVR as my primary platform for launching VR games.
In addition I use the following applications:

** fpsVR

FPS overlay and performance monitor. Attached to my left hand when it's pointed down.

** XSOverlay

Controller battery checker and desktop overlay attached to the back of my left hand.
Need to increase movement sensitivity in games to allow for scrolling with the joystick.
Possibly figure out a way to do scrolling without moving.

** OVR Advanced Settings

Various tweaks and playspace mover.

Bindings are all set up as chords, be sure to add an empty binding to each control that is used in the main area.
Otherwise it won't pick up on the controls used.

- Left Playspace Mover = Left A Touch + Left B Touch + Left Pad Click
- Right Playspace Mover = Right A Touch + Right B Touch + Right Pad Click
- Playspace Reset = Right A Touch + Right B Touch + Right Pad Click + Left A Touch + Left B Touch + Left Pad Click

Basically, lean your thumb into the two buttons and click the pad to move playspace using either hand.
Do it on both hands to reset your playspace.
This is set up with chords so that others using my controllers don't accidentally move themselves around.
Currently the right hand playspace mover doesn't work, not completely sure why..


